### ISSUE TITLE
404 file not found

### ISSUE THREAD

**Issue by marianoju** [clld/asjp-data#4]
I tried to download the ASJP Database following the link to on the website (see [Download](http://asjp.clld.org/download)) but server returns an error “404 Not Found” under http://asjp.clld.org/static/download/asjp-dataset.cldf.zip.

**Comment by xrotwang** [comment]
Yeah, sorry. I introduced this new type of download recently and didn't actually create the file on the server. The "regular" downloads, the usage of which is described in the [help document](http://asjp.clld.org/help) should work as always.

**Comment by xrotwang** [comment]
The download is now available.
