### ISSUE TITLE
Cantonese issues

### ISSUE THREAD

**Issue by dohliam** [clld/asjp-data#6]
There are multiple issues with the Cantonese data in [listss18.txt](https://github.com/clld/asjp-data/blob/master/listss18.txt), including several errors and some questionable vocabulary choices. I'm not sure if some of these might be artifacts of the source used (Huang's 1970 dictionary). I can edit this file directly if you are open to pull requests, but I will list the most significant issues below in case you would prefer to make these changes yourself.

    1 I	Noh //
    3 we	Nh deih //

Number 3 is missing a vowel in the first syllable -- it should be `Noh deih` (the first syllable is the same as the one in number 1).

However, it seems that the transcription used here does not account for tone markings, but nevertheless appears to include a residual "low tone" indicator ("h") from the Yale romanization system. As far as I understand, "h" in ASJPcode represents a voiceless and voiced glottal fricative, however here this is incorrect (as the "h" only indicates a low tone, not an /h/ sound). The same goes for other items in the list, for example number 8 `mh` should be `m` if tone is not taken into account, number 12 `yih` should be `yi` etc.

The other issue is vowel length, which is significant in Cantonese. I understand from the description of ASJPcode [here](https://www.researchgate.net/profile/Soren_Wichmann/publication/40853551_Automated_Classification_of_the_World%27s_Languages_A_Description_of_the_Method_and_Preliminary_Results/links/546373360cf2837efdb30a6e/Automated-Classification-of-the-Worlds-Languages-A-Description-of-the-Method-and-Preliminary-Results.pdf) that "long vowels ... are transcribed as if they were short vowels", however I believe this is still an error based on the transcription system you are using. The "short a" /ɐ/ and "long a" /a/ have both been transcribed as "a" here, despite being completely different phonemes. According to the table of ASJPcode vowels in the link above, it seems that the shorter vowel should be transcribed as "a" and the longer vowel as "E" in ASJPcode. Many words are affected by this -- for example, number 13 has been transcribed as `daih` but should probably be `dEi` (IPA is /ta:i˨/).

Also, the vowel transcribed as "u" here in words like 76 "yuh" (IPA: /jy:˩˧/) should be "i" in ASJPcode (it is the same vowel as that in French "tu" which you have transcribed as "ti". This is different from the vowel in 28 "peih fu" which is /u/, as well as the vowel in 24 "juN ji", which is /ʊ/.

Various vocabulary issues:

* `20 bird	jeuk jain //` There is no final /n/ here (it should be: `jeuk jai`)
* `32 grease	yauh, seuN yau //` The second gloss is a verb meaning "to grease / to apply oil to". I believe this is meant to only represent the noun "grease", so it should only include the first word (which should be transcribed as `yau` as per above -- as you can see there is an inconsistency or false distinction between "yauh" and "yau" in this entry, despite these being the same word)
* `52 heart	sam joN //` This seems overly specific, especially since 53 has just "gon" for liver (rather than "gon joN"). The same goes for 38, which lists "tauh hok" rather than just "tau" as might be expected
* `82 fire	fo juk //` This is the word for "fire" as in "an emergency", rather than the general word for fire. This should be changed to "fo" which would make more sense in this context
* The colour words in numbers 87-91 are very inconsistent -- some of them use the base colour word, some of them add "sik" ("colour") and some of them add "sik ge" ("the colour of"). To be meaningful, these should be standardized, for example either "luk", "woN", "bEk", "hak" (for green, yellow, white, black), or "luk sik", "woN sik", "bEk sik", "hak sik" etc.
* `95 full	fou dy~u fou hsih //` This one does not make any sense at all -- was this incorrectly copied over from a different language? Neither "fou", "dy~u" nor "hsih" are phonemes in Cantonese. The correct word should be "mun" (general meaning) or "bEu" (specifically for full after eating)
* `96 new	san ge //` The same problem as with the colour words applies here. There should be a standard approach for including adjectives: either the base form (as in number 97 "hou", not "hou ge") or adding adjectival/possessive marker "ge" (in which case words like 93 should be changed to "yit ge" instead of "yit" and 94 should be "duN ge, laN ge" rather than "laN, dunN"

**Comment by xrotwang** [comment]
asjp-data is not really collaboratively curated. So, I guess a PR with changes to `listss18.txt` is not the best way to get updates into a future `listsss19.txt`. I'll let Sören Wichmann - the primary curator of the ASJP data know about this issue, though.

**Comment by xrotwang** [comment]
@dohliam oh, and thanks for taking the time to let us know about these problems!

**Comment by dohliam** [comment]
@xrotwang Thanks for the reply! There are also some significant issues with Mandarin, which I was going to put in a different issue/PR, but I do understand if this does not fit your current workflow for the project.

Is there a preferred way to let Sören or the rest of the team know about issues or errors in the data that should be corrected? I checked the [Contribute](https://asjp.clld.org/contribute) page on the site and it only mentioned ways to add new languages rather than correcting existing data. (I assume this is something that is likely to come up again in the future since it is probably unavoidable for there to be some errors in a dataset of this size and scope.)

**Comment by xrotwang** [comment]
I guess, GitHub issue are the best way to collect this information. Sören knows about them, so he can collect the info. But there is no fixed release schedule for new versions, so no timeline on if or when changes may be incorporated.

**Comment by dohliam** [comment]
Understood -- that makes sense. Happy to continue opening issues here for reference so long as it doesn't cause any problems!

**Comment by xrotwang** [comment]
Moved to https://github.com/lexibank/asjp/issues/9
