### ISSUE TITLE
French issue

### ISSUE THREAD

**Issue by theroonba** [clld/asjp-data#7]
Surprised that such a common language should have so many apparent mistakes (more than 15% of the entire dataset), but here is a list anyway.

The word for 86. mountain "montagne", which should be (mo*ta5), is wrongly transcribed as "montage" (mo*taj)

Also, the word for 69. stand "se tenir debout", which should be (s3t3nird3bu), is wrongly transcribed with a v sound instead of a b (s3t3nird3vu). In addition, this really means "stand (yourself) up" in French.  You can also use simply "se tenir".  I'm not sure how reflexive verbs are treated elsewhere, but is it normal to have the reflexive part "se" in there as well?  Other examples are found in verbs such as "to sit" (s'asseoir).  The s' isn't really part of the root word for comparison.

The word for 74. star "étoile", which should be (etw~al), is wrongly transcribed (etw~ol).
The word for 11. one "un", which should be (e*), is wrongly transcribed as (oe*).
The word for 24. grain "graine", which should be (grEn), is wrongly transcribed as (gran).
The word for 36. feather "plume", which should be (plim), is wrongly transcribed as (ply~m) - which is almost unpronounceable with its lack of vowels.

The word for 39. ear "oreille", which should be (orEy), is wrongly transcribed as (ore).
The word for 55. eat (manger), which should be (ma*Ze), is wrongly transcribed as (ma*g) - wrong final consonant, and also missing the infinitive ending, which has been used with other verbs.
Verbs 60. (dormir), 61. (mourir) and 66. (venir), 68 (s'asseoir) are also missing the infinitive ending -r from the transcription.
The word for 64. fly (voler), which should be (vole), is wrongly transcribed as (vw~ale).
The word for 72. sun (soleil), which should be (solEy), is wrongly transcribed as (sole).
The word for 73. moon (lune), which should be (lin), is wrongly transcribed as (len).
The word for 76. rain (pluie), which should be (plw~i), is wrongly transcribed as (plui).
The word for 92. night (nuit), which should be (nw~i), is wrongly transcribed as (nui).
In the above 2 examples, I've treated /ɥ/ as a variant of /w/.

There also seem to be differences in how the diphthongal "oi" in French is treated with respect to preceding consonantal sounds.

In étoile (etw~a) and noir (nw~ar), the ~ connects the "w" to the preceding consonant, freeing up the "a" sound, and splitting the diphthong. However, in froid (fr~wa), this is not the case - the diphthong remains intact, and "fr" becomes one sound.  Possibly (frw~a) should be used here.

Note - some of the symbols have been mashed up - when I go to edit the post, they are fine, but in the copy that shows on the website, there are strikethroughs and all sorts of things, and several of the tilde symbols are missing.  Suffice to say, the numbers marked are transcribed wrongly.

**Comment by xrotwang** [comment]
Moved to https://github.com/lexibank/asjp/issues/8
